routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Admin route
Auth::routes();

/* CRUD Controllers */
Route::resource('banner', 'Admin\Banner\BannerController');
Route::resource('brand', 'Admin\Brand\BrandController');
Route::resource('product', 'Admin\Product\ProductController');
Route::group(['prefix' => 'product-specs/'], function () {
    Route::post('/add-group','Admin\Product\ProductSpecificationsController@addGroup');
    Route::post('/add-row','Admin\Product\ProductSpecificationsController@addRow');
    Route::post('/add-new-element','Admin\Product\ProductSpecificationsController@addNewElement');
    Route::post('/add-value','Admin\Product\ProductSpecificationsController@addValue');
});
Route::resource('product-type', 'Admin\ProductType\ProductTypeController');
/* End */


Route::resource('site', 'Admin\SiteController');
Route::post('/tool/upload','Tool\UploadController@upload');
Route::get('/home', 'HomeController@index');
Route::get('/', 'HomeController@index');
Route::resource('products', 'ProductsController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>SMARTBOOM</title>
    @csrf
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/skins/_all-skins.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.4.3/cropper.css">
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <link rel="stylesheet" href="{{ asset('css/photo-gallery.css') }}">
    <link rel="stylesheet" href="{{ asset('css/specifications.css') }}">
    @yield('css')
</head>
<body class="skin-blue sidebar-mini">
@if (!Auth::guest())
    <div class="wrapper">
        <header class="main-header">
            <a href="#" class="logo"><b>SMARTBOOM</b></a>
            <nav class="navbar navbar-static-top" role="navigation">
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li class="dropdown user user-menu">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg"
                                     class="user-image" alt="User Image"/>
                                <span class="hidden-xs">{!! Auth::user()->name !!}</span>
                            </a>
                        </li>
                        <li>
                            <a href="{!! url('/logout') !!}" class="btn "
                               onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                Выход
                            </a>
                            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        @include('layouts.sidebar')
        <div class="content-wrapper">
            @yield('content')
        </div>
        <footer class="main-footer" style="max-height: 100px;text-align: center">
            <strong><a href="#">GOLDCARROT</a> © 2019</strong>
        </footer>
    </div>
@else
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{!! url('/') !!}">
                    GOLDCARROT
                </a>
            </div>
            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{!! url('/login') !!}">Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
    @endif
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/js/adminlte.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.4.3/cropper.js"></script>
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
<script src="{{ asset('js/general-funs.js') }}"></script>
<script src="{{ asset('js/admin/general/cropper.js') }}"></script>
<script src="{{ asset('js/admin/general/main.js') }}"></script>
<script src="{{ asset('js/admin/product/photo-gallery.js') }}"></script>
<script src="{{ asset('js/admin/product/specifications/specifications.js') }}"></script>
<script src="{{ asset('js/admin/product/specifications/buttons.js') }}"></script>
    @yield('scripts')
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/menu.blade.php
<li class="{{ Request::is('banner*') ? 'active' : '' }}">
    <a href="{!! route('banner.index') !!}"><i class="fa fa-edit"></i><span>Банеры</span></a>
</li>
<li class="{{ Request::is('brand*') ? 'active' : '' }}">
    <a href="{!! route('brand.index') !!}"><i class="fa fa-edit"></i><span>Бренды</span></a>
</li>
<li class="{{ Request::is('product-type*') ? 'active' : '' }}">
    <a href="{!! route('product-type.index') !!}"><i class="fa fa-edit"></i><span>Типы Продуктов</span></a>
</li>
<li class="{{ (Request::is('product/*')||Request::is('product')) ? 'active' : '' }}">
    <a href="{!! route('product.index') !!}"><i class="fa fa-edit"></i><span>Продукты</span></a>
</li>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">
    <section class="sidebar">
        <ul class="sidebar-menu" data-widget="tree">
            @include('layouts.menu')
        </ul>
    </section>
</aside>